//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostCalc.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CostCalculatorDBEntities : DbContext
    {
        public CostCalculatorDBEntities()
            : base("name=CostCalculatorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationDetail> QuotationDetails { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    
        public virtual ObjectResult<GetAllLang_Result> GetAllLang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLang_Result>("GetAllLang");
        }
    
        public virtual ObjectResult<GetCategoriesDetails_Result> GetCategoriesDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategoriesDetails_Result>("GetCategoriesDetails");
        }
    
        public virtual ObjectResult<GetQuotationDetails_Result> GetQuotationDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuotationDetails_Result>("GetQuotationDetails");
        }
    }
}
